# Generated by Django 5.1 on 2024-10-23 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_testproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testproduct',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
